### ISSUE TITLE
Can't clone repo

### ISSUE THREAD

**Issue by baub** [xtacocorex/chip-python-aREST#10]
Thanks a lot for the great lib.

It looks like your repo has a private setting somewhere. I could not clone it. 
The only way I was able to use it was buy using the zip file or a fork.

I can help testing.

**Comment by xtacocorex** [comment]
What command did you use to try and clone the repo?

If you had it set for SSH, it will want ask for passcode.

Try `git clone https://github.com/xtacocorex/chip-python-aREST.git`

**Comment by xtacocorex** [comment]
I just looked at the readme and it's pointing to the SSH method, I'll get this updated when I get the CHIP I develop this powered on.
